// <auto-generated />
using System;
using GarageManagementSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GarageManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(GarageDbContext))]
    [Migration("20251106090000_AddCOGSToServiceOrder")]
    partial class AddCOGSToServiceOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            // Note: This Designer file is auto-generated and will be updated when running migrations
            // The actual model snapshot is managed by GarageDbContextModelSnapshot
#pragma warning restore 612, 618
        }
    }
}

